### ISSUE TITLE
Better Readme Needed

### ISSUE THREAD

**Issue by hossein-keshtkar** [azat-co/react#13]
It could have had a better and more specific Readme file. It is so confusing for someone new, who is unfamiliar with the project to figure out what is what and how to begin with the project.

**Comment by ujjwalpandey922** [comment]
Let me help with this one...
can you tell me more on how to go about it

**Comment by prajanravichandra** [comment]
i am interested to work on it..is this fixed?

**Comment by udayraj001** [comment]
The README could be more detailed and focused. For newcomers unfamiliar with the project, understanding its structure and figuring out how to get started can be quite challenging.

**Comment by azat-co** [comment]
@udayraj001 this repo is an old repo for React Quickly 1st edition... we have a new book (2nd edition) which is more up-to-date!
