### ISSUE TITLE
Sponsored issue: Change readme to make it summarize the library and its usage for the user

### ISSUE THREAD

**Issue by ujjwalpandey922** [azat-co/react#14]
Tell me know how you want the doc to look like and what all it should cover...

## Priority Support

- @ujjwalpandey922 is using  [Mintycode](https://mintycode.io) to fund this issue.
- If you would like to accept ![amount](https://imageupload.io/ib/zwkd2EaAY6YpPsg_1693209112.png) bounty for solving this issue join [Mintycode](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=7470112d-dae5-4a39-9e9e-acd3749065ec&owner=azat-co&name=react).
- Thank you in advance for helping.

[![mintycode](https://imageupload.io/ib/LvxMwrPxam1JW9e_1693210482.png)](https://mintycode.io)

**Comment by prajanravichandra** [comment]
i am interested to work on it..is this issue fixed or not?

**Comment by azat-co** [comment]
I think this is not needed because it's an old repo for an old book (React Quickly 1st edition). We have a new book now React Quickly 2nd edition.
